### ISSUE TITLE
PrivateCalendarViewerLeftSideBarを作る

### ISSUE THREAD

**Issue by chell-uoxou** [chell-uoxou/watnow-hackathon-2024-team3#46]
![image](https://github.com/user-attachments/assets/549f5a04-3534-4832-b048-91d422c35be0)
これ

### 作る
- components/common/ViewTitle
  - props: `title: string, subTitle?: string
`  - `subTitle`がundefinedならそのタグ出さない
- `<ViewTitle>`にはダミーで「あなたの」「カレンダー」を出しておく

**Comment by Mimimi19** [comment]
components/common/ViewTitle.tsx
はタイトルを表示するだけの関数なんですか？カレンダーとかは表示せずに

featuresでこの左ページを生成するコンポーネントを作成して
その中のcomponentsの中にタイトル生成とカレンダー生成下のボタンの生成のコンポーネントをまとめた方がいいのではないでしょうか？

**Comment by chell-uoxou** [comment]
| components/common/ViewTitle.tsx
はタイトルを表示するだけの関数なんですか？カレンダーとかは表示せずに

↑ですです　いろんなとこで使えるように

| featuresでこの左ページを生成するコンポーネントを作成して
その中のcomponentsの中にタイトル生成とカレンダー生成下のボタンの生成のコンポーネントをまとめた方がいいのではないでしょうか？

↑ `ViewTitle`以外は`features/`配下でOKです。カレンダーは`features/leftSideBar`
