### ISSUE TITLE
カレンダー押下でタイムラインの日付変更

### ISSUE THREAD

**Issue by saka-ko** [chell-uoxou/watnow-hackathon-2024-team3#73]
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/c437342c-26b1-461b-9bfb-b546378b9551">
ViewerLeftSidebarのカレンダーを使って、右側のタイムラインの日付を変更できるようにする。

**Comment by chell-uoxou** [comment]
#63 
> - **表示中の日付、スクロール位置など、表示セッション（`src/app/(app)/(calendar)/layout.tsx`のライフサイクルと同期 = リロードなどのたびにリセット）のJotai atomと扱うhookの作成**
👉 layoutでコンフリ起きそうだったからTODO
👉 左サイドバーの月表示カレンダーの選択とタイムラインの上のDateSwitcherをちゃんと同期したりできるようになる

の内容の土台を同時に作ってもらえると助かります！

表示セッションの名前は`calendarSession`にしましょう（`useCalendarSession`, `calendarSessionAtom`, `type CalendarSession`などの命名に使う）
